### ISSUE TITLE
[User Story] - Workout Routine Tracking

### ISSUE THREAD

**Issue by EdwardNajem** [EdwardNajem/Weyt#28]
When a user has a workout routine ready, They will begin using once they are doing their workout. The user will be able to check every set in every exercise.

- [ ] Workout Routine Start Display.
- [ ] Workout Routine Fetch
- [ ] Workout Routine Posting
